### ISSUE TITLE
Adding support for client certificate verification in SSLAdapter (patch included)

### ISSUE THREAD

**Issue by bb-migration** [cherrypy/cherrypy#1001]
Originally reported by: **Anonymous**

---

#### Enhancement
Adding support for client SSL certificate verification to wsgiserver's SSLAdapter

#### Reason
SSL support is critical for modern webservers to provide secure services to users.
However, there are times when applications running behind the webservers
need to determine which clients are actually communicating them. While HTTP
basic_auth can provide authentication, SSL provides another means to verify
client identity: client certification verification.

Similar to the server providing its SSL certificate, when client verification is in use, 
clients must provide a certificate signed by a CA that the server recognizes in order
for the client to be allowed to connect.

#### Changes
This patch adds another optional keyword argument to the SSLAdapter **`__init__()`** called
''client_CA''. ''client_CA'' is a string that contains a path to a CA certificate. When client_CA
is present, the SSLAdapter knows to perform client verification using this CA. When 
absent, SSLAdapter behaves as before, ie with no client verification. 

#### Bugs/Issues
While verification is performed correctly for both the ssl_pyopenssl SSLAdapter and the 
ssl_builtin SSLAdapter, the different implementations provide varying levels of support 
for SSL client environment variables that are traditionally provided by Apache's mod_ssl.
See this page for details [Mod_SSL Environment Variables](http://www.modssl.org/docs/2.8/ssl_reference.html#ToC25).

ssl_pyopenssl currently provides '''no''' client environment variables due to the fact that the
SSL handshake and thus the access to the client's certificate occurs at first data transfer - 
well after the environment variables are set by the SSLAdapter `wrap()` function.

ssl_builtin provides minimal environment variables. The major limiting factor is that
python's builtin ssl routines only expose a small amount of information about the 
certificates, and then only for the client certificate. This problem will be difficult to fix
if ssl_builtin must depend solely on python's ssl.

#### Patch
See attached Diff 

Reported by nmitchell@anl.gov

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1001

**Comment by ghost** [comment]
_Original comment by_ **Anonymous**:

---

I ran into a problem with this patch in the tick() method of the `HTTPServer` class in `wsgiserver/__init__.py`

The HTTPServer class has a list of socket errors which it "ignores", meaning that these errors do not cause the entire server to shut down.  Any other type of socket error causes CherryPy to exit, because the server believes that something has gone wrong with the socket it uses to accept incoming connections.  It uses the global "socket_errors_to_ignore" list to track these recoverable errors.

If a client connects with no certificate or a bad certificate when using the builtin ssl module, then an `ssl.SSLError` exception is raised.  This is a subclass of socket.error, with an error number value of 1, which is `EPERM`.  Unfortunately, `EPERM` is not currently on the `socket_errors_to_ignore` list, so a single bad client can cause the entire server to exit.

I've added `EPERM` to this list and submitted an updated patch.

**Comment by ghost** [comment]
_Original comment by_ **Tim Chase (Bitbucket: [gumnos](http://bitbucket.org/gumnos), GitHub: [gumnos](http://github.com/gumnos))**:

---

Is there a way to access the client-cert from within a request response?  Something like

```python
@cherrypy.expose
def hello(self):
    return repr(magic().getpeercert())
```

making use of [`getpeercert()`](http://docs.python.org/2/library/ssl.html#ssl.SSLSocket.getpeercert)

**Comment by dpeschman** [comment]
Was this ever merged?  @josephtate

**Comment by josephtate** [comment]
No. The original pr needed to be reworked to pass tests, and that work
never got finished.

**Comment by webknjaz** [comment]
@josephtate @jaraco is it possible to restore it from bitbucket?

**Comment by jaraco** [comment]
The code was merged in 1eb0b94e2bfe5bcd45aa1dce4c8455ccb7dbe4c4 and backed out in a89e31fc295bf9fb36326214bc9ab6c49df061f9.

**Comment by GP-S** [comment]
Hello guys! I was just wondering if this issue is still actual ?

**Comment by webknjaz** [comment]
@GP-S It looks like that patch has been reverted because of some issues. But it should be possible to modify `context` attribute of SSL Adapter you use upon initialization to have client verification enabled.

@jaraco might know more.

**Comment by jaraco** [comment]
I don't think there's much that can be done to revive the work that was attempted before. The project has since (a) consolidated wsgiserver2/3 modules and (b) extracted the wsgiserver functionality into cheroot. All of this refactoring means that the functionality that was created in those prior commits is largely unusable except as a reference.

I do see the reference to cherrypy/cheroot#52, which I believe re-implements this functionality in the newer codebase. It looks like maybe that PR was abandoned and is probably the best place to resume this activity.
