### ISSUE TITLE
CherryPy leaving hundreds of close_wait connections open

### ISSUE THREAD

**Issue by ghost** [cherrypy/cherrypy#1304]
Originally reported by: **Fred Rupert (Bitbucket: [fred_rupert](http://bitbucket.org/fred_rupert), GitHub: Unknown)**

---

CherryPy is leaving hundreds of close_wait connections open, I have to restart my CherryPy server every couple of days because it doesn't allow any more connections, and when I check netstat I see hundreds of close_wait connections.

I know this has been brought up a number of times here, does anyone know if a definitive cause has been found for it, or if there is a fix/work around for it?

TIA

---
- Bitbucket: https://bitbucket.org/cherrypy/cherrypy/issue/1304

**Comment by webknjaz** [comment]
@maxfischer2781

**Comment by awongssn** [comment]
Has this issue been resolve? I'm getting the same problem.
Is there a work around?

**Comment by webknjaz** [comment]
@awongssn it looks, it hasn't been fixed. If you have any more detail/investigation/STR, please document them here.

**Comment by tomholub** [comment]
I'm having a similar issue. I'm seeing stable amount of connections for days or weeks, then suddenly amounts of connections will start creeping up.

CherryPy==11.1.0 in a docker (Python 3.5.2, Ubuntu 16.04.3 LTS)

```
# netstat -ap | less
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:35875        *:*                     LISTEN      -               
tcp        0      0 *:rfe                   *:*                     LISTEN      1/python3.5     
tcp      506      0 27bbaa68cf7d:rfe        docker_proxy_lead:52148 CLOSE_WAIT  1/python3.5     
tcp      590      0 27bbaa68cf7d:rfe        docker_proxy_lead:48948 CLOSE_WAIT  1/python3.5     
tcp      147      0 27bbaa68cf7d:rfe        docker_proxy_lead:39138 CLOSE_WAIT  1/python3.5     
tcp      639      0 27bbaa68cf7d:rfe        docker_proxy_lead:54994 CLOSE_WAIT  1/python3.5     
tcp      147      0 27bbaa68cf7d:rfe        docker_proxy_lead:60312 CLOSE_WAIT  1/python3.5     
tcp      147      0 27bbaa68cf7d:rfe        docker_proxy_lead:59420 CLOSE_WAIT  1/python3.5     
tcp      147      0 27bbaa68cf7d:rfe        docker_proxy_lead:55092 CLOSE_WAIT  1/python3.5     
tcp      147      0 27bbaa68cf7d:rfe        docker_proxy_lead:35088 CLOSE_WAIT  1/python3.5     
tcp      585      0 27bbaa68cf7d:rfe        docker_proxy_lead:55120 CLOSE_WAIT  1/python3.5     
tcp      570      0 27bbaa68cf7d:rfe        docker_proxy_lead:51882 CLOSE_WAIT  1/python3.5     
tcp      147      0 27bbaa68cf7d:rfe        docker_proxy_lead:59042 CLOSE_WAIT  1/python3.5     
tcp      147      0 27bbaa68cf7d:rfe        docker_proxy_lead:57874 CLOSE_WAIT  1/python3.5     
tcp      590      0 27bbaa68cf7d:rfe        docker_proxy_lead:52924 CLOSE_WAIT  1/python3.5     
...
...

# netstat -ant | awk '{print $6}' | sort | uniq -c | sort -n
      1 FIN_WAIT2
      1 Foreign
      1 established)
      2 LISTEN
      8 ESTABLISHED
   2217 CLOSE_WAIT
```

Also notice the `Foreign Address` above. That is NGINX in another container running as a reverse proxy. If I run the same command in the NGINX container, there are very few connections listed (NGINX considers all these connections closed).

The issue is, this thing is hard to reproduce reliably. It will typically run for weeks without issues, and then suddenly it will start piling up CLOSE_WAIT connections. You can see that on the chart below:

![image](https://user-images.githubusercontent.com/6306961/38046332-0a498e82-32f2-11e8-99dc-738c23185232.png)

**The cherrypy app becomes completely unresponsive, eg `curl 127.0.0.1` hangs indefinitely, the moment CLOSE_WAIT connections start increasing as in the chart above.**

If there is any debugging code that I can use and report back the next time this happens, let me know.

**Comment by tomholub** [comment]
Again, app stopped being responsive as it started to accumulate connections in CLOSE_WAIT state:
![image](https://user-images.githubusercontent.com/6306961/38138530-082e6010-345e-11e8-8591-42b847fa5c27.png)
Let me know how could we debug this, it only happens when deployed in production for extended periods of time.

**Comment by webknjaz** [comment]
@tomholub have you tried increasing threads amount? any chance to reproduce this in an isolated container? can it be container-related? is it behind a reverse proxy? nginx?

**Comment by tomholub** [comment]
It's behind nginx. I cannot reproduce it reliably even with current setup -
it just sometimes starts happening.

I'll try to increase threads.

**Comment by webknjaz** [comment]
Please post here any findings you discover. I currently cannot reliably advise any debugging practice except for commonly knows ones.
BTW, please check the threads number when it happens again.

**Comment by tomholub** [comment]
Increasing threads (from 5 to 10) didn't help. Upgrading to CherryPy 14.0.1 didn't help.

I have put uwsgi in between cherrypy and nginx, eg instead of: `cherrypy <http> nginx <http> client` now it is `cherrypy <wsgi> uwsgi <http> nginx <http> client`.

I'll give it a few weeks to see if issues resurface. If they do, maybe some other part of our stack is causing it, in which case we could close this issue.

**Comment by hexaclock** [comment]
We experienced nearly the same scenario a while back. The issue is that CherryPy does not have a good way to handle HTTP Keep-Alive connections and so they begin to pile up with a default timeout time specified by the `server.socket_timeout` parameter. We resolved this problem by increasing the number of threads to 200 (probably a bit much), and setting the `response.headers.connection config` to always return a value of 'close'. This asks the browser to open a new TCP connection for each new request and tear it down after getting the response. We are currently experimenting with gunicorn and uwsgi, both of which appear to handle Keep-Alives in a better way than CherryPy.

**Comment by tomholub** [comment]
I don't think nginx as a reverse proxy does any keep-alive on the server side, so that may not be the only way to cause this.

**Comment by webknjaz** [comment]
@hexaclock any way to have a reproducible example/testcase for that? May I ask you to file an issue against [Cheroot](../../cheroot/issues/new)? I think I saw some problems in tests, this might help me to track those down and get rid of them.

**Comment by hexaclock** [comment]
@webknjaz Sure. I'll provide an minimum reproduction and test case (if possible), once I have a chance.

**Comment by hexaclock** [comment]
@webknjaz  Opened https://github.com/cherrypy/cheroot/issues/91

**Comment by sathishbabu96** [comment]
Facing the same issue. In my case, I make no requests to the cherrypy server. After a while(several hours) suddenly the CLOSE_WAIT connections start to pile up. I am using

CherryPy: 13.1.0
OS: CentOS Linux release 7.4.1708
Python: 3.6.3
Nginx as a reverse proxy

I cannot post the `netstat -anp | grep CLOSE_WAIT` command result. But the local and the foreign addresses are the same(which is localhost in my case).

**Comment by webknjaz** [comment]
I believe, https://github.com/cherrypy/cheroot/pull/199 addressed this.
