### ISSUE TITLE
tests relying on europoundUnicode are broken

### ISSUE THREAD

**Issue by jaraco** [cherrypy/cherrypy#1443]
In test_encoding, there is a variable created like so:

```
europoundUnicode = ntou(r'\x00\xa3')
```

Based on the name, I would expect this variable to be populated with a Unicode value containing the £ character. Instead, it gets populated with a value with this repr:

```
>>> from cherrypy import _cpcompat
>>> repr(_cpcompat.ntou(r'\x00\xa3'))
"u'\\\\x00\\\\xa3'"
>>> print(_cpcompat.ntou(r'\x00\xa3'))
\x00\xa3
```

That is, it's literally an ascii string containing backslashes, `x` and `a` characters, and a few digits. Surely this is a mistake.

**Comment by jaraco** [comment]
After correcting the mistake in the test, the tests now fail on Python 3 with this error:

```
======================================================================
ERROR: test_query_string_decoding (cherrypy.test.test_encoding.EncodingTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/test_encoding.py", line 122, in test_query_string_decoding
    self.getPage(ntob('/?param=') + europoundUtf8)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/helper.py", line 360, in getPage
    protocol, raise_subcls)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/webtest.py", line 278, in getPage
    raise_subcls)
  File "/Users/jaraco/Dropbox/code/public/cherrypy/cherrypy/test/webtest.py", line 554, in openURL
    skip_accept_encoding=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 960, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xa3' in position 12: ordinal not in range(128)

----------------------------------------------------------------------
```

**Comment by cincodenada** [comment]
This seems to be because of a change in Py3's urllib, which used to deal well with non-ASCII components in a URL, but doesn't any longer. See discussion on Python issue [here](https://bugs.python.org/issue3991), and conclusion (notably, the comment in the source) on a similar downstream issue [here](https://github.com/kevin1024/vcrpy/issues/185#issuecomment-304304652).

So I'm not sure the best way to actually test this in Py3, since the thing it's testing (unicode characters in URL strings) is no longer supported by `urllib`.

I've submitted #1614 as a step in the right direction, as the rest of the test is fine in Py3 (uses url-encoded characters). Not sure what the best actual solution would be here, as I'm not sure what the original bit was intended to test - does CherryPy want to support unencoded Unicode characters in URLs, or should it just fall to urllib's handling, which drops support for that in Py3?

**Comment by webknjaz** [comment]
@cincodenada I think it's okay to urlencode unicode query param in test, because anyway it should land in HTTP request as ASCII. Regarding server part, it must decode the symbol when passing it into HTTP handler. I guess, changing the test this way will fix the test, otherwise we could add urlencode to `openURL()` method in `test.webtest` module to make this behavior global.

**Comment by webknjaz** [comment]
It looks that this test case is invalid ([RFC 7230](http://httpwg.org/specs/rfc7230.html#uri) requires that the request line contains only ASCII). Browsers send percent-encoded URIs for unicode symbols and we handle this case.

I'm going to remove it, given that we've recently adjusted [`cheroot.server.HTTPRequest.read_request_line`](https://github.com/cherrypy/cheroot/blob/v5.8.3/cheroot/server.py#L730-L734) to follow RFCs more strictly.

If we'll decide to additionally support IRIs (RFC 3987), we'd need additional layer for [IRI<-->URI conversion](https://tools.ietf.org/html/rfc3987#section-3.1). AFAICS, the main difference it that they use angle brackets for wrapping byte representation rather than percent prefix (`<C2><A3>` vs. `%C2%A3`).
In my opinion, support for this is not needed currently, since HTTP clients already deal with the conversion on their side.

If you have any additional suggestions, feel free to share them here ;)
