### ISSUE TITLE
Wrong 'Content-Type' when retrieving gzip:ed js

### ISSUE THREAD

**Issue by darander** [cherrypy/cherrypy#1558]
While running CherryPy 10.0, I encounted an issue while trying to retrieve some gzipped javascript.
In order to save space on an embedded device, I'm only installing the `*.js.gz` files, not the unpacked `*.js`. After changing our html to directly request the `*.js.gz` files, the webapp stopped working.

CherryPy is configured to server those files by enabling `tools.staticdir.on`
The reason is that CherryPy sets 'Content-Type: application/x-gzip' when retrieving those files.
I believe that CherryPy should set:
```
Content-Type: application/json
Content-Encoding: gzip
```

**Comment by webknjaz** [comment]
Well, I think you might have called them `*.min.js` like everyone does

**Comment by darander** [comment]
Well, in my world, a *.min.js is a minified js-file, not a gzipped one...
Thus, they're not really the same. Our files are obviously also minified.

They're generated by `ng build --prod --aot` which gives as the *.js and *.js.gz files. 

So no, just using *.min.js isn't a solution for us.
At the same time, setting the correct Content-Type and Content-Encoding for all other file types  should be the correct thing to do anyway.

**Comment by webknjaz** [comment]
Oh.. I see.
Your solution isn't really obvious, so I cannot accept it right away. Anyway, let's move our discussion into PR.

**Comment by jaraco** [comment]
> I believe that CherryPy should set...

I'd feel better if I had more than one user's expectation that the headers should be as you propose, either a reference to a standard or documentation showing these headers are what a browser would expect or simply existing behavior in another more popular web server (like nginx).

Looking at the [docs for Content-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding), it is used to indicate an additional encoding of the entire body. In the case of serving a single file, the entire body is the file, which may be why your technique works, but it's confusing. Your tricking the client into thinking they're getting a Javascript file that's been encoded using gzip, rather than serving the gzip file directly. My guess is with this proposal implemented, if you were to curl that file, you'd get a `file.js.gz` file on your disk containing uncompressed javascript, and that's definitely not what you'd expect.

This proposed change also has the potential to interact badly with other behavior, like the `gzip` tool. Any change would necessarily need to document or test what is expected in such conditions.

> After changing our html to directly request the *.js.gz files, the webapp stopped working.

Do you have reason to expect that HTML is able to request gzipped js files? If your app doesn't work on other web servers, then it shouldn't magically work on CherryPy either, unless...

Perhaps what you should consider is writing a custom tool for CherryPy that does exactly what you're after - serving file.js.gz as file.js with gzip encoding. Then, your app could request 'file.js' and the server would serve the already gzipped encoding as you've described. You get the space saving on your embedded device and the browser gets javascript as it expected.

I can see some situations where this behavior should be the default for CherryPy, but only if that's consistent with the expectation from other web servers. Otherwise, this behavior should be a separate, opt-in tool.

**Comment by darander** [comment]
Yeah, there's is likely a better way to solve this.

**Comment by darander** [comment]
I'm reopening this issue, this time I've modified my problem description to:

Let the device have both *.js and *.js.gz files. However, to save space, make all *.js be empty. This should work, as long as the browser accepts gzip-ed files.
