### ISSUE TITLE
CherryPy WebFramework - security concerns

### ISSUE THREAD

**Issue by gabriel-yahav** [cherrypy/cherrypy#1573]
Hi , 

I'm not sure if that's the right place to ask such a question, but I'll try . 

I'm considering the possibility of using CherryPy on an embedded systems (as a web mgmt tool 

running on a network appliance), and I wonder about how the framework deals with significant security

issues , such as : XSS, CSRF, DoS attacks, Directory Traversing, session hijacking, etc...

I have not found yet any piece of information covering that issues . 

I'll be glad to get a feedback , 

Gabriel .

**Comment by webknjaz** [comment]
Hello Gabriel,

CherryPy is just an **HTTP** microframework, so it's up to user to care about everything else. So if you'll decide to use it, be ready to do some more coding.

Warm regards,
Sviatoslav.

**Comment by jaraco** [comment]
There are some tools to help, like the cherrypy_cors project, which seeks to facilitate the CORS standards for protecting against XSS. Also, because CherryPy handles URL parsing and payload decoding, such as with the JSON tool, that limits the places that user input needs to be handled by the developer, which helps security.

But on the whole, @webknjaz is right. Most of the issues you raise occur at higher levels in the stack than at the HTTP server, where CherryPy operates.
