### ISSUE TITLE
Content-Type header present when responding with 204

### ISSUE THREAD

**Issue by rmb938** [cherrypy/cherrypy#1657]
* **I'm submitting a ...**
[ X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

When setting the response status via `cherrypy.response.status` to `204` the Content-Type header is still present. 

* **What is the expected behavior?**

No Content-Type header when there is no content with a 204 status code

* **What is the motivation / use case for changing the behavior?**

Some clients and test frameworks (i.e WebTest: https://pypi.python.org/pypi/WebTest) will error when there is a Content-Type with status code 204.

* **Please tell us about your environment:**

- Cheroot version: 5.8.3
- CherryPy version: 11.0.0
- Python version: 3.6.2
- OS: Windows 10

**Comment by rmb938** [comment]
@webknjaz or @jaraco Any input on getting this fixed?

**Comment by webknjaz** [comment]
@rmb938 sorry for late answer. you are right.

You are referring to https://tools.ietf.org/html/rfc7230#section-3.3.2, which clearly states:

>    A server MAY send a Content-Length header field in a 304 (Not
   Modified) response to a conditional GET request (Section 4.1 of
   [RFC7232]); a server MUST NOT send Content-Length in such a response
   unless its field-value equals the decimal number of octets that would
   have been sent in the payload body of a 200 (OK) response to the same
   request.
>
>   A server MUST NOT send a Content-Length header field in any response
   with a status code of 1xx (Informational) or 204 (No Content).  A
   server MUST NOT send a Content-Length header field in any 2xx
   (Successful) response to a CONNECT request (Section 4.3.6 of
   [RFC7231]).


It should be fixed in cheroot, somewhere in this part: https://github.com/cherrypy/cheroot/blob/master/cheroot/server.py#L1039-L1056

**Comment by rmb938** [comment]
It seems like that bit of code is very similar to the version I am using, but let me try updating and see.

**Comment by rmb938** [comment]
Yup looks good in cheroot 6 and cherrypy 13.1

**Comment by webknjaz** [comment]
Cool, thanks for checking. I've also noticed that we actually have a test for this: https://github.com/cherrypy/cheroot/blob/5bc7b39/cheroot/test/test_conn.py#L579-L584 (JFI)
