### ISSUE TITLE
CherryPy uses _pyio incorrectly

### ISSUE THREAD

**Issue by ryflyio** [cherrypy/cherrypy#1704]
Attempting to use CherryPy on Cygwin has revealed that CherryPy imports a private module, _pyio. "Outside" use of _pyio this way is not supported.

CherryPy should use a different module or interface for this functionality (https://github.com/cherrypy/cheroot/blob/86c6b246ec7cb704c6f96123556db1a083301634/cheroot/makefile.py#L5). 

A side-effect of fixing this issue is that this may help CherryPy run on Cygwin once again.

See https://bugs.python.org/issue32287 for more discussion or context.

**Comment by webknjaz** [comment]
Hello, this ticket should be open under [Cheroot repo](/cherrypy/cheroot), so that it won't get lost/out of track.

P.S. It looks like regression, which happens to be caused by this patch:
https://github.com/cherrypy/cheroot/commit/270b0eab39b13c864fd271b9f49f09f7edb62216#diff-d99a7689c2159eab73db39f9e5b89a1dL5
PR is welcome.
