### ISSUE TITLE
Error reading cherrypy.request.body in a PATCH method

### ISSUE THREAD

**Issue by alf-tierno** [cherrypy/cherrypy#1710]
-->

* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

A bug

* **What is the current behavior?**
Making a PATCH method, e.g. with python request. When at server (cherrypy) it is read the body content it fails because a method recieves more parameters than expected. See PATCH bellow for solving problem

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

```python
# At server 
#########
import yaml
import cherrypy
class StringGenerator(object):
    @cherrypy.expose
    def generate(self):
        indata = yaml.load(cherrypy.request.body)
        return str(indata)
if __name__ == '__main__':
    cherrypy.quickstart(StringGenerator())
```

```python
# At client:
#######
import request
url_server = 'http://localhost:8080/generate'
request.patch(url_server, data='{key: value}', headers={'content-type': 'application/yaml'})
```

* **What is the expected behavior?**
Obtained just '{key: value}' text

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Cheroot version: ????
- CherryPy version: 3.5.0-2build1
- Python version: 3.5.2
- OS: Ubuntu 16.04
- Browser: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

The error happens at file `/usr/lib/python3/dist-packages/cherrypy/wsgiserver/wsgiserver3.py`
at `KnownLengthRFile` class,  method read
Use this `PATCH` for solving the problem. I cannot see where this code is at `cherrypy` to make a pull request

```diff
--- ./wsgiserver/wsgiserver3.py-back    2018-05-18 10:59:32.164590936 +0200
+++ ./wsgiserver/wsgiserver3.py 2018-05-18 11:04:15.774831363 +0200
@@ -320,9 +320,12 @@
         self.rfile = rfile
         self.remaining = content_length

-    def read(self, size=None):
+    def read(self, size=None, fp_out=None):
         if self.remaining == 0:
-            return b''
+            if fp_out is None:
+                return b''
+            else:
+                return None
         if size is None:
             size = self.remaining
         else:
```

**Comment by webknjaz** [comment]
> Cheroot version: ????
> CherryPy version: 3.5.0-2build1

Wow! That's way outdated!
I recall seeing a problem where PATCH method wasn't in variable listing methods with bodies, but that was fixed probably a few years ago.

> I cannot see where this code is

It's here https://github.com/cherrypy/cheroot/blob/9d73226/cheroot/server.py#L320-L338

[Current version of CherryPy is 15.0.0](https://pypi.org/p/cherrypy). WSGI and low-level HTTP server stuff has been moved out into a separate distribution Cheroot around v8.0.0, that's why you don't see it in the current master.


So the best course of action for you now is to upgrade to version 15.0.0 and see how it goes. The issue you're talking about is most probably fixed there.

I'm going to close this issue, if the issue persists please [file a bug report against Cheroot](https://github.com/cherrypy/cheroot/issues/new?template=Bug_report.md) itself with a more up-to-date references.

**Comment by alf-tierno** [comment]
Yes it is true. This problem is not present with version 15 of cherrypy.
The problem is that at Ubuntu16.04 LTS server, the available deb package (python3-cherrypy3) installs this version. Is there any way to obtain a more modern debian package?
I mean, in case you do not want to use neither pip nor easey-intall

**Comment by webknjaz** [comment]
@alf-tierno I think you should reach out to the Ubuntu's package maintainer and ask them to package new versions or you could package it yourself, maybe even publish an unofficial PPA.

Personally I don't see any point in using OS packages, since it's not a good idea to mess up with a system global installation of python anyway.
On the other hand, using virtualenv+pip or maybe even some kind of container (pure LXC, docker) would be beneficial. I also enjoy using pyenv with virtualenv plugin, which is just perfect for development and allows me to not rely on system installation or `sudo` privileges (it's in userspace), nor depend on whatever Python version the OS distributor decided to support (I install quite a variety of versions).

We don't intend to provide distributions for every package manager possible. But we have distribution with metadata, which makes it possible for other people to package CherryPy any way they want.
(https://github.com/cherrypy/cherrypy/issues/1711#issuecomment-390652507)

The only supported way of installing CherryPy is by using `pip install` (which we already automatically test across a wide matrix of distro+python combos).
If you find someone willing to do (create, support, maintain) such third-party packaging, we'll gladly include a reference into our docs.
