### ISSUE TITLE
'501 Not Implemented' with traceback

### ISSUE THREAD

**Issue by blare-ski** [cherrypy/cherrypy#1853]
**I'm submitting a ...**
- [x] bug report

**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

In SeaMonkey 2.53.1, when opening https://id.fedoraproject.org/openid/Consent by pressing ctrl-shift-t, an error appears:

```python-traceback
501 Not Implemented

Server does not support this operation

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/usr/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/site-packages/ipsilon/util/page.py", line 85, in __call__
    return op(*args, **kwargs).encode('utf-8')
  File "/usr/lib/python3.7/site-packages/ipsilon/providers/common.py", line 105, in root
    return op(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/ipsilon/providers/common.py", line 91, in GET
    raise cherrypy.HTTPError(501)
cherrypy._cperror.HTTPError: (501, None)

Powered by CherryPy 18.1.2
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshots and logs of the problem. If you can, show us your code.**

The 'Consent' may only be asked of a new FAS user once.

**What is the expected behavior?**
Either a successful resolution of https://id.fedoraproject.org/openid/Consent, or an error message without any tracebacks.

**What is the motivation / use case for changing the behavior?**

A traceback often means that some problem has occurred.

**Please tell us about your environment:**

- OS: Fedora 31

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, e.g. stackoverflow, gitter, etc.)

see also https://pagure.io/ipsilon/issue/310

**Comment by webknjaz** [comment]
Reproducing this does not require Ctrl+Shift+T. I see it when just clicking on that link (not being authenticated). I guess that the authors of the `ipsilon` provider expect POST requests but you send GET.
Anyway, this is not an exception that CherryPy produces but an error that ipsilon itself raises and there's nothing we can do because it's a third-party project that is not a part of CherryPy, nor is related in any way.

The reason the traceback is revealed to the users is that they (id.fedoraproject.org) clearly run CherryPy in development mode.
They should switch to using [production mode](https://docs.cherrypy.org/en/latest/config.html#environments) (with something like `cherrypy.config.update({'environment': 'production'})` that has a different default error page template. On top of that, they wire-up their own error page output matching their website theme.
